feat: convert xml to protobuf IDL and json targets
wenchy/tableau pull request #1
Opened 2022-01-25 03:59 UTC by huiEric

2022-02-10 02:22 UTC, wenchy commented on internal/confgen/confgen.go
> +func NewGenerator(protoPackage, indir, outdir string, setters ...options.Option) (*options.Options, *Generator) {
It's not good to return options, as the options is input parameters.

2022-02-10 08:25 UTC, wenchy requested changes

2022-02-10 08:25 UTC, wenchy commented on internal/importer/xml.go
> +type XmlImporter struct {
naming: `XmlImporter` -> `XMLImporter`

2022-02-10 08:25 UTC, wenchy commented on internal/importer/xml.go
> +	replaced_str = keywordRegexp.ReplaceAllString(replaced_str, `$1$2`)
naming convention: `replaced_str` -> `replacedStr`

2022-02-10 08:25 UTC, wenchy commented on internal/importer/xml.go
> +	x.sheetMap[root.LocalName()] = sheet
treated as only one sheet in a XML file?

2022-02-10 08:25 UTC, wenchy commented on internal/importer/xml.go
> +		// 3. {Type}int32 -> [Type]int32
Need this?

2022-02-10 08:25 UTC, wenchy commented on internal/importer/xml.go
> +					return fmt.Errorf("%s is not scalar type in node %s attr %s type %s", matches[1], nav.LocalName(), attrName, t)
errors: replace all `fmt.Errorf` to `errors.Errorf`
refetr: https://github.com/pkg/errors

2022-02-10 08:25 UTC, wenchy commented on internal/protogen/exporter.go
> +func (x *sheetExporter) exportField(depth int, tagid int, field *tableaupb.Field, prefix string) error {
There is no need to care about **prefix**, as it was already nested.

2022-02-10 08:25 UTC, wenchy commented on internal/protogen/parser.go
> +		}
?

2022-02-10 08:25 UTC, wenchy commented on internal/protogen/parser.go
> +		index := strings.Index(trimmedNameCell, field.Type) + len(field.Type)
intent?

2022-02-10 08:25 UTC, wenchy commented on internal/protogen/protogen.go
> +}
1. format!
2. intent?

2022-02-10 08:25 UTC, wenchy commented on internal/protogen/protogen.go
> -
?

2022-02-10 08:25 UTC, wenchy commented on internal/protogen/protogen.go
> +}
boring stuff! You'd better use Format type to check the suffix.

2022-02-10 08:25 UTC, wenchy commented on internal/protogen/protogen.go
> +		if filepath.Ext(entry.Name()) != gen.GetSuffix() {
use Format type to check

2022-02-10 08:25 UTC, wenchy commented on options/options.go
> +
What for?

2022-02-10 08:25 UTC, wenchy commented on proto/tableau/protobuf/tableau.proto
> +  int32 list_max_len = 15; // non-incell list max len
not used?

2022-02-10 08:25 UTC, wenchy commented on tableau.go
> +	atom.Log.Infof("options inited: %+v", opts)
log level: `Infof` -> `Debugf`

2022-02-10 08:25 UTC, wenchy commented on tableau.go
> +	atom.Log.Infof("options inited: %+v", opts)
log level: `Infof` -> `Debugf`

2022-02-10 08:25 UTC, wenchy commented on test/protoconf/excel/test_conf.proto
>        ConfType type = 1 [(tableau.field) = {name:"Type"}];
?

2022-02-10 08:25 UTC, wenchy commented on test/scripts/gen_pb.sh
> +gen_pb $test_indir/xml
two packages: `testexcel` and `testxml`

2022-02-10 08:25 UTC, wenchy commented on test/tableau_test.go
> +func Test_Xml2JSON(t *testing.T) {
naming: `Xml` -> `XML`

2022-02-11 01:45 UTC, huieric commented on internal/protogen/exporter.go
> +func (x *sheetExporter) exportField(depth int, tagid int, field *tableaupb.Field, prefix string) error {
The same messages in different trees should be exported to different message.
So we need the `prefix` to provide their parents name and construct a nest message name.

2022-02-11 01:45 UTC, huieric commented on test/scripts/gen_pb.sh
> +gen_pb $test_indir/xml
if excel and xml are two packages, there exists a problem. Some common messages and enum predefined in `common.proto`, `time.proto`, etc. cannot stay in one package, which means some enums may need to define twice.

2022-02-11 01:45 UTC, huieric commented on internal/protogen/protogen.go
> +		if filepath.Ext(entry.Name()) != gen.GetSuffix() {
What is `Format type`?

2022-02-11 01:45 UTC, huieric commented on internal/protogen/protogen.go
> +}
In this way how can i skip excel file when i only want to generate xml proto?

2022-02-11 01:45 UTC, huieric commented on internal/importer/xml.go
> +	x.sheetMap[root.LocalName()] = sheet
For simplicity we just view one xml file as one sheet in this version.

2022-02-11 03:58 UTC, wenchy commented on internal/protogen/exporter.go
> +		nestedMsgName := prefix + "/" + msgName
`"/"` -> `"."`

2022-02-11 04:12 UTC, merged